name: Build & Deploy Flask to Azure Web App (stackiq-web)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Sanity check Flask app
        run: python - << 'PY'
from app import app
print("Flask app imported OK:", bool(app))
PY

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: stackiq-web
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STACKIQ_WEB }}
          package: .
          enable-oryx-build: true
